// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(RestaurantAPIContext))]
    partial class RestaurantAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PointOfSale.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Image = "japchae.png",
                            Price = 13.99,
                            Quantity = 1,
                            Title = "Japchae"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Image = "jajangmyeon.png",
                            Price = 14.99,
                            Quantity = 1,
                            Title = "Jajangmyeon"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Image = "janchi_guksu.png",
                            Price = 12.99,
                            Quantity = 1,
                            Title = "Janchi Guksu"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Image = "budae_jjigae.png",
                            Price = 14.99,
                            Quantity = 1,
                            Title = "Budae Jjigae"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Image = "naengmyeon.png",
                            Price = 12.99,
                            Quantity = 1,
                            Title = "Naengmyeon"
                        },
                        new
                        {
                            Id = 6,
                            Category = 5,
                            Image = "soda.png",
                            Price = 2.5,
                            Quantity = 1,
                            Title = "Soda"
                        },
                        new
                        {
                            Id = 7,
                            Category = 5,
                            Image = "iced_tea.png",
                            Price = 3.5,
                            Quantity = 1,
                            Title = "Iced Tea"
                        },
                        new
                        {
                            Id = 8,
                            Category = 5,
                            Image = "tea.png",
                            Price = 4.0,
                            Quantity = 1,
                            Title = "Hot Tea"
                        },
                        new
                        {
                            Id = 9,
                            Category = 5,
                            Image = "coffee.png",
                            Price = 4.0,
                            Quantity = 1,
                            Title = "Coffee"
                        },
                        new
                        {
                            Id = 10,
                            Category = 5,
                            Image = "milk.png",
                            Price = 5.0,
                            Quantity = 1,
                            Title = "Milk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
